#os: windows
language: node_js
node_js:
  - "10.16.3"
dist: trusty
sudo: required

before_script:
  - npm install

script: 
  - npm run test-headless
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $FINDING_FALCONE_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: docs
  target_branch: ghPagesServiceWithSubject
  on:
    branch: ghPagesServiceWithSubject